2021-10-05T09:51:16.3328140+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T09:51:16.3448590+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T09:51:16.3500630+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T09:51:16.3529130+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T09:51:16.3534930+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T10:13:21.7289190+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T10:13:21.7403850+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T10:13:21.7441130+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T10:13:21.7450810+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T10:13:21.7459460+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T10:19:44.0378590+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T10:19:44.0469950+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T10:19:44.0504550+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T10:19:44.0517090+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T10:19:44.0523980+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T10:56:31.1283280+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T10:56:31.1406090+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T10:56:31.1467700+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T10:56:31.1487150+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T10:56:31.1496240+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T11:09:35.2341620+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T11:09:35.2516310+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T11:09:35.2587090+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T11:09:35.2610070+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T11:09:35.2621370+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T11:35:02.0197130+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T11:35:02.0288440+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T11:35:02.0325640+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T11:35:02.0351790+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T11:35:02.0374910+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T11:36:44.2416080+02:00 0HMC7SDJV3I4C:00000001 [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:36:56.9909080+02:00 0HMC7SDJV3I4C:00000002 [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:40:19.3578590+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T11:40:19.3712020+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T11:40:19.3777820+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T11:40:19.3809680+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T11:40:19.3814160+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T11:41:41.5705120+02:00 0HMC7SGIHBUJK:00000012 [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:42:00.6227320+02:00 0HMC7SGIHBUJK:00000015 [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:42:01.8350680+02:00 0HMC7SGIHBUJK:00000018 [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:42:13.6774430+02:00 0HMC7SGIHBUJK:0000001E [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:42:29.9482420+02:00 0HMC7SGIHBUJO:00000001 [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:42:35.8461510+02:00 0HMC7SGIHBUJO:00000002 [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:44:01.5338500+02:00 0HMC7SGIHBUJP:0000000A [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:44:03.3929520+02:00 0HMC7SGIHBUJP:0000000C [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:44:04.6849050+02:00 0HMC7SGIHBUJP:0000000E [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:47:30.4617630+02:00 0HMC7SGIHBUJQ:00000003 [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:47:31.0758940+02:00 0HMC7SGIHBUJQ:00000005 [INF] Billett ikke funnet (f224cc46)
2021-10-05T11:47:31.6962630+02:00 0HMC7SGIHBUJQ:00000007 [INF] Billett ikke funnet (f224cc46)
2021-10-05T12:08:20.3412860+02:00 0HMC7SGIHBUK2:00000001 [INF] Billett ikke funnet (f224cc46)
2021-10-05T16:32:32.6720260+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T16:32:32.6847270+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T16:32:32.6902900+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T16:32:32.6919940+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T16:32:32.6935220+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T16:51:28.5416010+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T16:51:28.5580568+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T16:51:28.5583454+02:00  [INF] Content root path: "C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json" (b5d60022)
2021-10-05T16:51:30.2488690+02:00 80000051-0000-f800-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at DeezSalings.DAL.ReiseRepository.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in /Users/minh/Documents/GitHub/Webapp-Oblig1/DAL/ReiseRepository.cs:line 86
   at DeezSalings.Controller.ReiseController.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in /Users/minh/Documents/GitHub/Webapp-Oblig1/Controller/ReiseController.cs:line 51
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T16:52:37.5301579+02:00 80000081-0002-f400-b63f-84710c7967bb [INF] Feil i inputvalidering (06f553d7)
2021-10-05T16:52:52.0409700+02:00 800000ba-0006-f900-b63f-84710c7967bb [INF] Billett ikke funnet (f224cc46)
2021-10-05T17:21:45.2467516+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T17:21:45.2625349+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T17:21:45.2628663+02:00  [INF] Content root path: "C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json" (b5d60022)
2021-10-05T17:36:16.2865054+02:00 80000062-0000-f800-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at DeezSalings.DAL.ReiseRepository.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\DAL\ReiseRepository.cs:line 86
   at DeezSalings.Controller.ReiseController.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\Controller\ReiseController.cs:line 51
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T17:36:18.0453523+02:00 8000006f-000a-fa00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at DeezSalings.DAL.ReiseRepository.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\DAL\ReiseRepository.cs:line 86
   at DeezSalings.Controller.ReiseController.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\Controller\ReiseController.cs:line 51
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T18:06:59.8091331+02:00 80000030-0008-fe00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at DeezSalings.DAL.ReiseRepository.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\DAL\ReiseRepository.cs:line 86
   at DeezSalings.Controller.ReiseController.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\Controller\ReiseController.cs:line 51
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T18:07:26.2356122+02:00 80000081-0004-ff00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at DeezSalings.DAL.ReiseRepository.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\DAL\ReiseRepository.cs:line 86
   at DeezSalings.Controller.ReiseController.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\Controller\ReiseController.cs:line 51
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T18:07:44.6326370+02:00 80000030-0001-fe00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at DeezSalings.DAL.ReiseRepository.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\DAL\ReiseRepository.cs:line 86
   at DeezSalings.Controller.ReiseController.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\Controller\ReiseController.cs:line 51
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T18:07:58.6292516+02:00 8000002e-0005-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at DeezSalings.DAL.ReiseRepository.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\DAL\ReiseRepository.cs:line 86
   at DeezSalings.Controller.ReiseController.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\Controller\ReiseController.cs:line 51
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T18:08:17.7996047+02:00 80000030-0005-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at DeezSalings.DAL.ReiseRepository.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\DAL\ReiseRepository.cs:line 86
   at DeezSalings.Controller.ReiseController.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\Controller\ReiseController.cs:line 51
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T18:08:20.6501262+02:00 80000061-0008-fb00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at DeezSalings.DAL.ReiseRepository.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\DAL\ReiseRepository.cs:line 86
   at DeezSalings.Controller.ReiseController.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json\Controller\ReiseController.cs:line 51
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T19:54:17.2695334+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T19:54:17.2788801+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T19:54:17.2789764+02:00  [INF] Content root path: "C:\Users\charl\Documents\GitHub\Webapp-Oblig1_1\package-lock.json" (b5d60022)
2021-10-05T21:06:53.6136900+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T21:06:53.6262120+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T21:06:53.6314240+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T21:06:53.6331870+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T21:06:53.6346980+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T21:10:54.9646290+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T21:10:54.9778410+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T21:10:54.9825390+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T21:10:54.9841540+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T21:10:54.9844870+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T21:52:09.2949630+02:00 0HMC86FDHBSD2:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at DeezSalings.DAL.ReiseRepository.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in /Users/minh/Documents/GitHub/Webapp-Oblig1/DAL/ReiseRepository.cs:line 86
   at DeezSalings.Controller.ReiseController.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in /Users/minh/Documents/GitHub/Webapp-Oblig1/Controller/ReiseController.cs:line 51
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T21:59:29.7864010+02:00 0HMC86FDHBSD4:0000001C [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at DeezSalings.DAL.ReiseRepository.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in /Users/minh/Documents/GitHub/Webapp-Oblig1/DAL/ReiseRepository.cs:line 86
   at DeezSalings.Controller.ReiseController.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in /Users/minh/Documents/GitHub/Webapp-Oblig1/Controller/ReiseController.cs:line 51
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T22:43:47.0510760+02:00 0HMC86FDHBSDI:00000006 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at DeezSalings.DAL.ReiseRepository.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in /Users/minh/Documents/GitHub/Webapp-Oblig1/DAL/ReiseRepository.cs:line 86
   at DeezSalings.Controller.ReiseController.valgtAvreisetid(Int32 id, Int32 day, Int32 month, Int32 year) in /Users/minh/Documents/GitHub/Webapp-Oblig1/Controller/ReiseController.cs:line 51
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T22:52:40.2543760+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T22:52:40.2651440+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T22:52:40.2690240+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T22:52:40.2706840+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T22:52:40.2717910+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T22:57:16.4684220+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T22:57:16.4765430+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T22:57:16.4798400+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T22:57:16.4812950+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T22:57:16.4826670+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T22:59:45.0039560+02:00 0HMC88ARCA4E3:00000004 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at DeezSalings.DAL.ReiseRepository.Reiserute(Int32 id) in /Users/minh/Documents/GitHub/Webapp-Oblig1/DAL/ReiseRepository.cs:line 118
   at DeezSalings.Controller.ReiseController.Reiserute(Int32 id) in /Users/minh/Documents/GitHub/Webapp-Oblig1/Controller/ReiseController.cs:line 46
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-05T23:07:53.3922420+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T23:07:53.4004160+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T23:07:53.4034720+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T23:07:53.4050940+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T23:07:53.4057420+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T23:23:02.5002970+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T23:23:02.5094710+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T23:23:02.5127620+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T23:23:02.5140340+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T23:23:02.5150790+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T23:27:53.8246370+02:00 0HMC88P847R0V:0000000B [INF] Feil i inputvalidering (06f553d7)
2021-10-05T23:28:31.5230570+02:00 0HMC88P847R0V:0000000F [INF] Feil i inputvalidering (06f553d7)
2021-10-05T23:29:10.9878830+02:00 0HMC88P847R0V:00000013 [INF] Feil i inputvalidering (06f553d7)
2021-10-05T23:30:11.2317360+02:00 0HMC88P847R0V:00000018 [INF] Feil i inputvalidering (06f553d7)
2021-10-05T23:30:47.7690750+02:00 0HMC88P847R0V:0000001D [INF] Feil i inputvalidering (06f553d7)
2021-10-05T23:31:50.6251420+02:00 0HMC88P847R0U:0000001C [INF] Feil i inputvalidering (06f553d7)
2021-10-05T23:32:11.8742410+02:00 0HMC88P847R0U:00000020 [INF] Feil i inputvalidering (06f553d7)
2021-10-05T23:33:37.4707950+02:00 0HMC88P847R0V:00000023 [INF] Feil i inputvalidering (06f553d7)
2021-10-05T23:37:53.4614230+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T23:37:53.4735670+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T23:37:53.4777170+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T23:37:53.4800080+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T23:37:53.4815530+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T23:58:00.8100480+02:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-10-05T23:58:00.8185010+02:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-10-05T23:58:00.8223810+02:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-10-05T23:58:00.8235590+02:00  [INF] Hosting environment: "Development" (c3307c92)
2021-10-05T23:58:00.8238770+02:00  [INF] Content root path: "/Users/minh/Documents/GitHub/Webapp-Oblig1" (b5d60022)
2021-10-05T23:58:30.1867850+02:00 0HMC89CPG0RGK:00000009 [INF] Feil i inputvalidering (06f553d7)
